#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill $HOME/Wallpaper/nord_lights.png &
picom &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/forest/launch.sh

#Workspaces
bspc monitor -d I II III IV V

#other stuffs
bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
