#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
#feh --bg-fill $HOME/Wallpaper/nord_lights.png &
nm-applet &
nitrogen --restore &
picom &
#xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
#polybar, available themes = gradient, forest
$HOME/.config/polybar/gradient/launch.sh

#Workspaces
bspc monitor -d I II III IV V

#other stuffs
bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a Eog state=floating follow=on
bspc rule -a Blueman-manager state=floating
bspc rule -a flameshot state=floating
wmname LG3D
